# docker-compose.yml
version: '3'
services:
  app:
    build:
      args:
        user: isiburger
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: isi-burger
    container_name: isi-burger-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - isi-burger
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: isi-burger-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - isi-burger-data:/var/lib/mysql
    networks:
      - isi-burger

  nginx:
    image: nginx:alpine
    container_name: isi-burger-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - isi-burger
    depends_on:
      - app

networks:
  isi-burger:
    driver: bridge

volumes:
  isi-burger-data:
    driver: local